owner: nyaone
repo: remote-status-monitor

sites:
  # 服务主体
  - name: Misskey
    slug: misskey
    icon: https://status.nya.one/icons/network-connection.svg
    url: https://nya.one
  - name: Matrix
    slug: matrix
    icon: https://status.nya.one/icons/comments.svg
    url: https://matrix.nya.one/_matrix/client/versions
  - name: 文件存储
    slug: object-storage
    icon: https://status.nya.one/icons/folder-cloud.svg
    url: https://sh.nfs.pub/nyaone/ff02042e-524e-48e8-bb27-17621d96b13a.png
  - name: 搜索引擎
    slug: search-engine
    icon: https://status.nya.one/icons/search.svg
    url: https://meilisearch.nya.one
  - name: 媒体代理
    slug: media-proxy
    icon: https://status.nya.one/icons/transactions.svg
    url: https://o.n1mp.org
    expectedStatusCodes:
      - 400
  # 周边生态
  - name: 喵家中继
    slug: relay
    icon: https://status.nya.one/icons/nodes.svg
    url: https://relay.nya.one/actor
  - name: 邮件系统
    slug: mail-system
    icon: https://status.nya.one/icons/mail.svg
    url: mx.nya.one
    port: 25
    check: "tcp-ping"
  # 辅助功能
  - name: API Wrap
    slug: api-wrap
    icon: https://status.nya.one/icons/plug-2.svg
    url: https://api.nya.one
  - name: 备用域名
    slug: backup-domain
    icon: https://status.nya.one/icons/a-tag-add.svg
    url: https://n1.homes
  # 开发环境
  - name: Misskey (开发环境)
    slug: misskey-dev
    icon: https://status.nya.one/icons/network-connection.svg
    url: https://dev.nya.one
  - name: Matrix (开发环境)
    slug: matrix-dev
    icon: https://status.nya.one/icons/comments.svg
    url: https://dev-matrix.nya.one/_matrix/client/versions
  - name: API Wrap (开发环境)
    slug: api-wrap-dev
    icon: https://status.nya.one/icons/plug-2.svg
    url: https://dev-api.nya.one

assignees: # Users to assign downtime issues (optional)
  - Candinya

status-website:
  cname: status.nya.one
  logoUrl: https://docs.nya.one/assets/logo/round.png
  favicon: https://docs.nya.one/assets/logo/round.png
  faviconSvg: https://docs.nya.one/assets/logo/round.svg
  themeUrl: https://status.nya.one/blue.css
  name: NyaOne Status
  introTitle: "**喵窝** 状态监控"
  introMessage: 喵窝与周边服务的在线状态监控页面
  navbar:
    - title: 状态
      href: /
    - title: 喵窝
      href: https://nya.one

i18n:
  activeIncidents: 活跃的事件
  allSystemsOperational: 所有系统正常运行
  incidentReport: "事件 #$NUMBER 报告 →"
  activeIncidentSummary: 在 $DATE 开始，有 $POSTS 个帖子
  incidentTitle: 事件 $NUMBER 详细信息
  incidentDetails: 事件的详细信息
  incidentFixed: 已修复
  incidentOngoing: 进行中
  incidentOpenedAt: 开始于
  incidentClosedAt: 结束于
  incidentViewOnGitHub: 在 GitHub 上查看
  incidentCommentSummary: 由 $AUTHOR 发布于 $DATE
  incidentBack: ← 返回全部事件列表
  pastIncidents: 过去的事件
  pastIncidentsResolved: 在 $MINUTES 分钟内解决，共有 $POSTS 个帖子
  liveStatus: 实时状态
  overallUptime: "总体在线时间: $UPTIME"
  overallUptimeTitle: 总体在线时间
  averageResponseTime: "平均响应时间: $TIME 毫秒"
  averageResponseTimeTitle: 平均响应时间
  sevelDayResponseTime: 7 天响应时间
  responseTimeMs: 响应时间 (毫秒)
  up: 在线
  down: 离线
  degraded: 降级
  ms: 毫秒
  loading: 加载中…
  navGitHub: GitHub
  footer: ©️ 2024 NyaOne 版权所有。 [项目]($REPO) 由 [Upptime](https://upptime.js.org) 强力驱动。
  rateLimitExceededTitle: 超出速率限制
  rateLimitExceededIntro: 您已超出您一小时内可以执行的请求数，因此请您稍后再访问本页面。或者，您可以添加 GitHub 个人访问令牌以继续使用此网站。
  rateLimitExceededWhatDoesErrorMean: 这个错误意味着什么？
  rateLimitExceededErrorMeaning: 这个网站使用 GitHub API 来获取关于我们网站状态的实时数据。默认情况下， GitHub 允许每个 IP 地址每小时发送 60 个请求，而您已经耗尽了它们。
  rateLimitExceededErrorHowCanFix: 我应该如何修复它？
  rateLimitExceededErrorFix: 您可以再等待一个小时，以重置您的 IP 地址限制。或者，您也可以添加您的 GitHub 个人访问令牌，它会为您提供额外的每小时 5,000 个请求。
  rateLimitExceededGeneratePAT: 了解如何生成个人访问令牌
  rateLimitExceededHasSet: 您设置了个人访问令牌。
  rateLimitExceededRemoveToken: 删除令牌
  rateLimitExceededGitHubPAT: GitHub 个人访问令牌
  rateLimitExceededCopyPastePAT: 复制并粘贴您的个人访问令牌
  rateLimitExceededSaveToken: 保存令牌
  errorTitle: 出现了一个错误
  errorIntro: 获取最新状态细节时出现了一个错误。
  errorText: 您可以稍后再试。
  errorHome: 回到主页
  pastScheduledMaintenance: 过去计划的维护
  scheduledMaintenance: 计划的维护
  scheduledMaintenanceSummaryStarted: 在 $DATE 开始，持续 $DURATION 分钟
  scheduledMaintenanceSummaryStarts: 在 $DATE 开始，持续 $DURATION 分钟
  startedAt: 开始于
  startsAt: 开始于
  duration: 持续时间
  durationMin: $DURATION 分钟
  incidentCompleted: 已完成
  incidentScheduled: 已计划
  duration24H: 一天
  duration7D: 一周
  duration30D: 一个月
  duration1Y: 一年
  durationAll: 全部
  locale: zh-CN

commitMessages:
  commitAuthorName: "Nya Cat"
  commitAuthorEmail: "95197277+nya-cat@users.noreply.github.com"
